Uniref refactor
ebi-uniprot/uniprot-store pull request #132
Opened 2021-01-12 16:39 UTC by LeonardoGonzales

Changes to reflect model Update to add RepresentativeMember in the UniRefLightEntry object

2021-01-13 16:16 UTC, jieluo321 reviewed
I wonder if we need the test cases for DatasetUniRefConverterUtil

2021-01-13 16:17 UTC, jieluo321 reviewed
if you think there are tests covering DatasetUniRefConverterUtil, then i am fine with it

2021-01-21 09:11 UTC, eddturner requested changes

2021-01-21 09:11 UTC, eddturner commented on spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniref/converter/DatasetUniRefEntryLightConverter.java
> +            Optional<String> accession =
is this the same as:

```java
member.getUniProtAccessions().stream().map(Value::getValue).findFirst().ifPresent(acc -> {
                UniRefMemberIdType type = getUniProtKBIdType(member.getMemberId(), acc);
                builder.membersAdd(acc + "," + type.getMemberIdTypeId());
                builder.memberIdTypesAdd(type);
});
```

?

2021-01-21 09:11 UTC, eddturner commented on uniprot-config/src/main/resources/return-fields-config/uniref-return-fields.json
>    },
maybe i'm wrong, but i think we need to update the entry filtering paths? in uniparc-search-fields.json because the paths will have changed

2021-01-21 09:11 UTC, eddturner commented on spark-indexer/src/main/java/org/uniprot/store/spark/indexer/uniref/converter/DatasetUniRefConverterUtil.java
> +class DatasetUniRefConverterUtil {
are there tests for this class?

2021-01-28 15:27 UTC, merged